In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/lifestyle.csv")

In [4]:
df

,State,Percentage Affected by Smoking,Percentage Affected by Obesity,Percentage Affected by No Excercise
0,Alabama,43.94,36.69,30.67
1,Alaska,43.22,30.10,19.63
2,Arizona,40.35,30.60,22.13
3,Arkansas,47.06,37.59,30.97
4,California,33.45,26.38,20.98
5,Colorado,40.43,23.45,16.39
6,Connecticut,39.47,28.17,22.36
7,Delaware,42.27,34.37,26.78
8,District of Columbia,34.72,25.15,19.58
9,Florida,41.89,31.17,26.80
10,Georgia,37.64,33.01,26.24
11,Hawaii,39.40,25.18,19.86
12,Idaho,38.19,29.60,20.47
13,Illinois,38.29,32.25,24.56
14,Indiana,45.03,34.79,27.35
15,Iowa,41.03,36.28,22.93
16,Kansas,41.85,35.25,22.53
17,Kentucky,50.40,37.58,32.44
18,Louisiana,43.17,37.08,30.83
19,Maine,49.73,30.78,22.53
20,Maryland,36.02,31.61,22.95
21,Massachusetts,38.50,26.40,22.43
22,Michigan,45.38,33.89,23.85
23,Minnesota,41.05,30.58,20.54
24,Mississippi,42.85,39.88,32.01
25,Missouri,44.08,35.80,26.11
26,Montana,44.48,27.78,22.74
27,Nebraska,39.73,34.80,23.77
28,Nevada,41.46,30.50,24.97
29,New Hampshire,45.18,30.09,21.51
30,New Jersey,37.06,26.28,28.53
31,New Mexico,40.71,32.93,22.16
32,New York,36.31,28.04,23.84
33,North Carolina,43.03,33.79,23.90
34,North Dakota,42.73,36.62,22.26
35,Ohio,45.77,34.64,25.45
36,Oklahoma,44.52,35.63,27.20
37,Oregon,43.12,30.59,19.29
38,Pennsylvania,42.86,31.77,23.99
39,Rhode Island,42.16,28.41,25.34
40,South Carolina,43.59,34.95,26.73
41,South Dakota,44.17,30.87,23.99
42,Tennessee,45.49,34.91,30.88
43,Texas,36.08,35.51,25.61
44,Utah,24.95,28.41,17.49
45,Vermont,44.05,28.22,18.93
46,Virginia,37.78,31.23,21.95
47,Washington,38.11,29.57,17.56
48,West Virginia,49.54,39.98,28.20
49,Wisconsin,42.72,32.93,21.77
50,Wyoming,45.14,29.71,21.67