In [1]:
import pandas as pd
import glob
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Getting all csv files from state_alcohol_consumption data folder 
# and combining into single dataframe to get ready for data wrangling

# Get CSV files list from a folder
path = '../Data/cancer_data_if/state_alcohol_consumption'
csv_files = glob.glob(path + "/*.csv")

# Read each CSV file into DataFrame
# This creates a list of dataframes
df_list = (pd.read_csv(file) for file in csv_files)

# Concatenate all DataFrames
big_df   = pd.concat(df_list, ignore_index=True)

In [3]:
big_df

,ID,Year,LocationAbbr,LocationDesc,Class,Topic,Indicator,Response,DataSource,Data_Value_Unit,...,StratificationType,IndicatorId,LocationOrder,ParentStateDisplayOrder,FootnoteType,FootNoteSymbol,FootnoteText,URL,DatasourceAbbr,Agency
0,1919087.0,2011.0,US,"All States, DC and Territories (median) **",Alcohol Consumption,Heavy Drinking,Heavy drinkers (adult men having more than two...,Yes,BRFSS,%,...,Overall,_RFDRHV4,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1918483.0,2011.0,UW,All States and DC (median) **,Alcohol Consumption,Heavy Drinking,Heavy drinkers (adult men having more than two...,Yes,BRFSS,%,...,Overall,_RFDRHV4,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1773748.0,2011.0,AL,Alabama,Alcohol Consumption,Heavy Drinking,Heavy drinkers (adult men having more than two...,Yes,BRFSS,%,...,Overall,_RFDRHV4,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1776212.0,2011.0,AK,Alaska,Alcohol Consumption,Heavy Drinking,Heavy drinkers (adult men having more than two...,Yes,BRFSS,%,...,Overall,_RFDRHV4,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1779117.0,2011.0,AZ,Arizona,Alcohol Consumption,Heavy Drinking,Heavy drinkers (adult men having more than two...,Yes,BRFSS,%,...,Overall,_RFDRHV4,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,SuggestedCitation,NaN,"Centers for Disease Control and Prevention, Na...",https://www.cdc.gov/brfss/brfssprevalence/,NaN,NaN
722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Prevalence Data and Data Analysis Tools,/brfss/data_tools.htm,NaN,NaN
723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Behavioral Risk Factor Surveillance System (BR...,/brfss/index.html,NaN,NaN
724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Division of Population Health,/nccdphp/dph/index.html,NaN,NaN
725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Survey Data & Documentation,/brfss/data_documentation/index.htm,NaN,NaN

In [4]:
# dropped id, question, response, columns, footnotes and references columns
alcohol_df = big_df.drop(big_df.columns[[0,6,7,8,9,10,12,13,17,18,19,20,21,22,23,24,25,26,27]], axis=1)

In [5]:
alcohol_df.head()

,Year,LocationAbbr,LocationDesc,Class,Topic,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size
0,2011.0,US,"All States, DC and Territories (median) **",Alcohol Consumption,Heavy Drinking,6.6,NaN,NaN,53.0
1,2011.0,UW,All States and DC (median) **,Alcohol Consumption,Heavy Drinking,6.6,NaN,NaN,51.0
2,2011.0,AL,Alabama,Alcohol Consumption,Heavy Drinking,5.1,4.3,5.9,298.0
3,2011.0,AK,Alaska,Alcohol Consumption,Heavy Drinking,7.4,6.2,8.6,248.0
4,2011.0,AZ,Arizona,Alcohol Consumption,Heavy Drinking,6.9,5.7,8.0,378.0

In [6]:
#list of all unique values from each column
for col in alcohol_df:
    print(alcohol_df[col].unique())

[2011.   nan 2012. 2013. 2014. 2015. 2016. 2017. 2018. 2019. 2020. 2021.]
['US' 'UW' 'AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'DC' 'FL' 'GA' 'HI'
 'ID' 'IL' 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'MO'
 'MT' 'NE' 'NV' 'NH' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OH' 'OK' 'OR' 'PA' 'RI'
 'SC' 'SD' 'TN' 'TX' 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'WY' 'GU' 'PR' nan 'VI']
['All States, DC and Territories (median) **'
 'All States and DC (median) **' 'Alabama' 'Alaska' 'Arizona' 'Arkansas'
 'California' 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia'
 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont'
 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam'
 'Puerto Rico' nan 'Virgin Islands']
['Alcohol Consumption' nan]
['Heavy Drinking' nan]
[ 6.6  5.1  7.4  6.9  6.2  6.7  9.6  7.6  8.5  6.   8.1  5.4  5.7  7.8
  7.9  7.1  4.7  7.3  7.5  6.8  8.   5.8  5.6  6.5  5.5  7.2  5.9  3.4
  7.   4.1  8.3  6.4  3.9  9.8  5.3  nan  6.1  5.2  6.3  4.6  5.   4.9
  3.6  3.5  4.3  8.2  4.2  7.7  8.6  3.3  4.5  8.8  9.   4.8  9.1  8.7
  3.8 11.1  4.4  3.7  8.9  8.4  9.5  9.3  9.2  9.4  9.9  4. ]
[ nan  4.3  6.2  5.7  4.9  6.   8.   6.8  5.4  6.5  5.1  7.3  5.3  7.2
  5.   7.1  6.3  4.   7.   5.6  6.9  5.9  4.7  6.4  5.8  2.3  6.1  3.6
  7.4  3.2  8.5  4.6  4.5  5.5  3.3  5.2  4.2  4.4  3.8  7.7  6.6  4.8
  2.9  3.1  6.7  3.5  7.6  2.6  3.9  4.1  3.   8.2 94.5 89.7 94.1 93.4
 93.7 93.5 93.2 93.6 88.9 93.8 91.4 93.9 92.9 93.3 93.1 92.3 91.  94.2
 91.9 92.8 93.  94.6 91.3 92.4 94.8 94.7 95.1 94.4 95.9 90.8 92.7 87.5
 91.2 92.2 90.5 91.7 92.5 92.  92.6 91.5 95.6 89.8 90.  89.4 89.9 94.
 89.2 90.1 91.6 95.8 95.7 91.1 90.9 90.4 92.1 95.  94.3 90.7 90.6 90.2
 95.3 88.8 94.9 89.1 89.  95.5 95.2]
[ nan  5.9  8.6  8.   7.4  6.7  8.7 11.1  8.3  7.1  7.2  9.6  6.8  9.
  6.5  7.   8.5  7.8  5.4  8.4  8.1  7.9  6.6  6.4  7.5  6.2  7.3  7.7
  6.9  4.4  4.6  9.3  4.7  6.1  6.   4.9  9.7  8.2  5.7  9.4  5.8  5.3
  4.3  4.   4.1  5.6  5.   7.6  5.5  6.3  4.8  3.9  4.5  8.8  5.1 10.
 10.7  3.7  4.2 10.4 95.9 93.1 95.6 94.8 94.6 95.8 92.9 94.7 93.3 95.5
 94.9 95.3 95.1 94.5 96.  93.8 94.1 94.  96.4 95.2 94.4 96.2 96.6 93.7
 94.3 96.1 96.3 96.8 93.2 94.2 97.1 92.8 95.  90.4 93.  93.9 92.3 95.4
 93.5 97.  92.  93.6 95.7 91.9 92.1 96.5 93.4 92.5 92.4 96.7 91.6 91.7
 92.7 91.5 91.4 92.6]
[   53.    51.   298.   248.   378.   189.  1063.   737.   393.   292.
   349.   770.   464.   544.   295.   370.   369.   425.   823.   387.
   482.   855.   501.  1343.   665.  1034.   281.   321.   668.  1391.
   384.   463.   760.   444.   424.   478.   245.   506.   330.   407.
   594.   697.   404.   131.   495.   341.   896.   163.   383.   102.
   257.    nan   345.   268.   371.   180.   766.   723.   541.   239.
   252.   601.   285.   300.   400.   398.   632.   637.  1278.   535.
   689.   236.   320.   610.  1049.   342.   470.   756.   420.   331.
   512.   229.   657.   297.   353.  1018.   310.   642.   412.   182.
   473.   414.   441.   375.   949.   164.   282.   116.   258.   234.
   343.   238.   192.   652.   773.   397.   304.   319.  2075.   578.
   311.   318.   456.   417.   916.   365.   250.   548.   631.   894.
   874.   235.   664.   864.   628.   484.   515.   363.   418.   568.
   273.   458.   546.   339.   532.   308.   155.   552.   491.   429.
   426.   736.   294.   118.   219.   322.   350.   732.   197.   455.
   764.   409.   286.   591.   267.   569.   288.   494.   609.   576.
   922.   481.   978.   119.   283.   467.  1139.   259.   596.   317.
   355.   503.   255.   536.   346.   313.   139.   763.   490.   468.
   466.   296.   159.   202.  7180.  3214.  7055.  4785. 10835. 11422.
 10368.  3667.  3400.  8482.  4204.  6271.  5279.  4810.  5511.  5624.
 20585.  8013.  4126.  8068. 11262.  7933.  7996. 14987.  5560.  6676.
  5407. 15990.  2602.  6201. 10176.  6072. 10778.  6001.  4497. 10808.
  6422.  4620.  5119.  5500. 10414.  6673.  5393. 12893. 10511.  5710.
  7806. 14283.  5525.  5465.  4951.  1479.  5049.    54.  6269.  2579.
  9736.  4858.  9601. 12539.  9841.  3582.  3160. 31793.  4787.  7085.
  4709.  4246.  9982.  6514. 10739.  9342.  4631.  8886. 16211.  7190.
 10699. 14803.  4655.  5367. 13816.  3838.  5664.  6786.  5433. 29466.
  5707.  5159. 11210.  6236.  4572.  6088.  4812.  9983.  5271.  5534.
 10323. 10058.  5686.  8051. 12728.  6698.  4510.  4125.  1400.  5359.
  1133.  6020.  2750. 13516.  4805.  7929.  8177.  9228.  3598.  3273.
 19033.  5268.  4403.  4957. 12285.  6801. 18929.  7734.  4112.  8427.
 11823.  5997.  9738. 14992.  4516.  6849.  5277. 13682.  3320.  5001.
 10344.  5749. 10473.  4257.  6224. 11038.  5925.  4580.  5822.  4909.
 10008.  6293.  5164. 10686.  9452.  5554.  8560. 11653.  5134.  4977.
  4032.  1308.  4122.  5930.  2455.  7121.  4758. 10201.  7502.  9369.
  4590.  3756. 13212.  8122.  6766.  3323.  4724.  6746.  8072.  9687.
  7777.  4389.  9584. 15543.  5730.  9160. 15204.  5298.  5622.  4609.
 13104.  2852.  5044.  2698.  6042. 30242.  4096.  5109. 11627.  4771.
  4985.  5486.  4878.  9739.  6296.  4560.  9645.  9812.  5719.  9234.
 11446.  4557.  4339.  4056.  1433.  4381.    52.    50.  6253.  2534.
  7800.  4807. 10057.  8016.  7979.  3384.  2167. 14309.  6349.  4814.
  4910.  7822.  8732.  9991.  7280.  4004.  9856. 15414.  6661.  9458.
 13597.  4616.  6592.  5703. 14222.  2473.  5026.  5360. 11930.  3736.
  5042. 12050.  5503.  5160.  5938.  5213.  6147.  6119.  5446. 10472.
 10925.  5513.  8827. 11296.  4905.  4305.  4212.  2126.  5537.  4800.
  3095.  8767.  4629.  4095.  8689.  7703.  3464.  2897. 10102.  7756.
  6800.  5216.  3193.  7309.  8367.  9415.  3479.  3984.  9523. 11654.
  6075.  6517. 13727.  5853.  8209.  5494. 13016.  2146.  5408.  6320.
 12313.  5057.  3991. 12627.  4292.  4595.  4598.  4550.  3495.  6137.
  3995.  9214.  9990.  5529.  8389. 11004.  5462.  4369.  4285.  1940.
  4541.  4115.  4658.  9256.  4717.  5866.  8791.  6961.  3107.  2656.
  6877.  6809.  5987.  2820.  8522.  8469. 15610.  4839.  4275. 10279.
 13207.  6774.  8121. 13743.  3959. 10977.  5504. 13266.  2414.  6629.
  5745. 32765.  4356.  5253. 12363.  4652.  4551.  5538.  4749.  8245.
  6559.  4173.  9260.  9614.  5579.  8521. 11404.  6213.  5318.  3879.
  1452.  3762.  1158.]

In [7]:
alcohol_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 726 entries, 0 to 725
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   605 non-null    float64
 1   LocationAbbr           605 non-null    object
 2   LocationDesc           605 non-null    object
 3   Class                  605 non-null    object
 4   Topic                  605 non-null    object
 5   Data_Value             605 non-null    float64
 6   Low_Confidence_Limit   583 non-null    float64
 7   High_Confidence_Limit  583 non-null    float64
 8   Sample_Size            605 non-null    float64
dtypes: float64(5), object(4)
memory usage: 51.2+ KB

In [8]:
#dropped null values from alcohol_df
alcohol_df = alcohol_df.dropna(how='any',axis=0)
alcohol_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 583 entries, 2 to 714
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   583 non-null    float64
 1   LocationAbbr           583 non-null    object
 2   LocationDesc           583 non-null    object
 3   Class                  583 non-null    object
 4   Topic                  583 non-null    object
 5   Data_Value             583 non-null    float64
 6   Low_Confidence_Limit   583 non-null    float64
 7   High_Confidence_Limit  583 non-null    float64
 8   Sample_Size            583 non-null    float64
dtypes: float64(5), object(4)
memory usage: 45.5+ KB

In [9]:
alcohol_df

,Year,LocationAbbr,LocationDesc,Class,Topic,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size
2,2011.0,AL,Alabama,Alcohol Consumption,Heavy Drinking,5.1,4.3,5.9,298.0
3,2011.0,AK,Alaska,Alcohol Consumption,Heavy Drinking,7.4,6.2,8.6,248.0
4,2011.0,AZ,Arizona,Alcohol Consumption,Heavy Drinking,6.9,5.7,8.0,378.0
5,2011.0,AR,Arkansas,Alcohol Consumption,Heavy Drinking,6.2,4.9,7.4,189.0
6,2011.0,CA,California,Alcohol Consumption,Heavy Drinking,6.2,5.7,6.7,1063.0
...,...,...,...,...,...,...,...,...,...
710,2021.0,WI,Wisconsin,Alcohol Consumption,Heavy Drinking,8.2,90.7,92.9,5318.0
711,2021.0,WY,Wyoming,Alcohol Consumption,Heavy Drinking,6.7,92.2,94.4,3879.0
712,2021.0,GU,Guam,Alcohol Consumption,Heavy Drinking,5.5,92.7,96.3,1452.0
713,2021.0,PR,Puerto Rico,Alcohol Consumption,Heavy Drinking,3.9,95.2,97.0,3762.0
714,2021.0,VI,Virgin Islands,Alcohol Consumption,Heavy Drinking,5.4,92.2,97.0,1158.0

In [10]:
# Getting all csv files from state_vegetable_consumption folder

path = '../Data/cancer_data_if/state_vegetable_consumption'
csv_files = glob.glob(path + "/*.csv")

df_list = (pd.read_csv(file) for file in csv_files)

veg_df   = pd.concat(df_list, ignore_index=True)

In [11]:
veg_df

,ID,Year,LocationAbbr,LocationDesc,Class,Topic,Indicator,Response,DataSource,Data_Value_Unit,...,StratificationType,IndicatorId,LocationOrder,ParentStateDisplayOrder,FootnoteType,FootNoteSymbol,FootnoteText,URL,DatasourceAbbr,Agency
0,2270083.0,2013.0,US,"All States, DC and Territories (median) **",Fruits and Vegetables,Vegetable Consumption,Consumed vegetables less than one time per day...,One or more times per day,BRFSS,%,...,Overall,_VEGLT1,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2269635.0,2013.0,UW,All States and DC (median) **,Fruits and Vegetables,Vegetable Consumption,Consumed vegetables less than one time per day...,One or more times per day,BRFSS,%,...,Overall,_VEGLT1,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2069715.0,2013.0,AL,Alabama,Fruits and Vegetables,Vegetable Consumption,Consumed vegetables less than one time per day...,One or more times per day,BRFSS,%,...,Overall,_VEGLT1,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2073596.0,2013.0,AK,Alaska,Fruits and Vegetables,Vegetable Consumption,Consumed vegetables less than one time per day...,One or more times per day,BRFSS,%,...,Overall,_VEGLT1,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2077512.0,2013.0,AZ,Arizona,Fruits and Vegetables,Vegetable Consumption,Consumed vegetables less than one time per day...,One or more times per day,BRFSS,%,...,Overall,_VEGLT1,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,SuggestedCitation,NaN,"Centers for Disease Control and Prevention, Na...",https://www.cdc.gov/brfss/brfssprevalence/,NaN,NaN
325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Prevalence Data and Data Analysis Tools,/brfss/data_tools.htm,NaN,NaN
326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Behavioral Risk Factor Surveillance System (BR...,/brfss/index.html,NaN,NaN
327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Division of Population Health,/nccdphp/dph/index.html,NaN,NaN
328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,RelatedLinks,NaN,Survey Data & Documentation,/brfss/data_documentation/index.htm,NaN,NaN

In [12]:
veg1_df = veg_df.drop(veg_df.columns[[0,6,7,8,9,10,12,13,17,18,19,20,21,22,23,24,25,26,27]], axis=1)
veg1_df.head()

,Year,LocationAbbr,LocationDesc,Class,Topic,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size
0,2013.0,US,"All States, DC and Territories (median) **",Fruits and Vegetables,Vegetable Consumption,76.9,NaN,NaN,53.0
1,2013.0,UW,All States and DC (median) **,Fruits and Vegetables,Vegetable Consumption,77.1,NaN,NaN,51.0
2,2013.0,AL,Alabama,Fruits and Vegetables,Vegetable Consumption,74.2,72.5,75.9,4489.0
3,2013.0,AK,Alaska,Fruits and Vegetables,Vegetable Consumption,80.8,79.0,82.6,3462.0
4,2013.0,AZ,Arizona,Fruits and Vegetables,Vegetable Consumption,76.2,73.7,78.8,3032.0

In [13]:
veg1_df = veg1_df.dropna(how='any',axis=0)
veg1_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 264 entries, 2 to 317
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   264 non-null    float64
 1   LocationAbbr           264 non-null    object
 2   LocationDesc           264 non-null    object
 3   Class                  264 non-null    object
 4   Topic                  264 non-null    object
 5   Data_Value             264 non-null    float64
 6   Low_Confidence_Limit   264 non-null    float64
 7   High_Confidence_Limit  264 non-null    float64
 8   Sample_Size            264 non-null    float64
dtypes: float64(5), object(4)
memory usage: 20.6+ KB

In [14]:
for col in veg1_df:
    print(veg1_df[col].unique())

[2013. 2015. 2017. 2019. 2021.]
['AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'DC' 'FL' 'GA' 'HI' 'ID' 'IL'
 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'MO' 'MT' 'NE'
 'NV' 'NH' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC' 'SD'
 'TN' 'TX' 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'WY' 'GU' 'PR' 'VI']
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam' 'Puerto Rico'
 'Virgin Islands']
['Fruits and Vegetables']
['Vegetable Consumption']
[74.2 80.8 76.2 72.  82.7 80.9 77.8 71.1 79.1 79.2 76.3 76.9 79.6 76.
 73.1 73.2 77.1 75.2 67.3 82.3 78.  79.9 75.3 76.4 69.4 75.7 79.5 76.7
 83.2 78.6 78.5 77.6 72.6 73.7 74.7 83.7 78.7 75.5 83.5 81.8 75.8 69.9
 72.2 81.1 71.9 81.4 82.2 80.6 79.3 81.  73.3 77.7 75.4 69.  81.7 68.8
 80.7 77.9 78.4 72.5 75.6 76.5 74.6 73.9 77.4 80.5 80.  82.4 78.3 73.5
 79.4 82.6 82.8 87.7 81.9 79.  84.1 83.  76.1 87.6 83.3 81.6 82.  83.1
 84.9 86.5 79.7 84.4 80.2 81.3 82.9 83.6 84.2 78.1 87.2 83.4 84.7 54.
 80.4 78.8 76.6 77.3 80.1 80.3 74.5 87.5 84.5 74.8 79.8 77.  82.1 77.2
 73.  55.6 81.5 77.5 83.8 74.4 86.9 76.8 75.9 86.2 70.6 53.4 67.8]
[72.5 79.  73.7 70.1 81.6 80.  76.2 69.3 76.9 78.1 74.9 75.3 78.  74.3
 71.8 76.4 73.8 65.1 81.1 76.8 78.8 74.1 75.1 67.7 78.3 75.6 81.8 77.5
 77.1 76.7 71.1 72.4 73.4 82.3 71.9 73.9 77.2 78.6 82.2 77.3 80.7 74.4
 72.3 66.9 74.  70.6 78.9 69.5 80.4 79.4 77.4 78.2 79.7 71.5 77.  67.1
 80.5 75.2 79.2 74.2 78.4 81.3 76.6 76.5 70.7 82.1 74.6 72.  75.7 79.1
 72.1 70.  82.  86.2 79.3 80.6 77.6 82.6 79.8 79.6 86.4 81.7 81.2 83.5
 85.  82.9 80.2 82.4 80.9 81.4 82.7 85.9 83.1 82.5 80.3 79.5 83.3 70.2
 52.  76.3 78.5 75.  77.7 81.5 72.7 83.4 75.4 81.9 74.7 77.8 79.9 81.
 80.1 78.7 54.  76.1 75.8 72.6 73.5 84.7 66.3 51.2 60.2]
[75.9 82.6 78.8 74.  83.9 81.9 79.4 73.  81.3 80.2 77.7 78.4 74.3 74.7
 77.8 76.5 69.6 83.6 79.3 81.1 76.4 71.1 77.3 80.7 81.6 84.5 79.8 79.2
 78.9 74.2 75.  76.1 85.1 74.5 77.5 79.9 80.6 84.8 82.9 77.2 76.  81.4
 72.9 77.  73.7 83.3 81.  82.4 81.7 83.7 80.  83.  75.1 70.9 80.4 78.5
 70.7 78.3 82.3 84.1 74.4 76.7 85.  75.8 81.8 79.6 84.  74.9 80.5 82.1
 80.3 84.4 84.6 89.2 85.7 83.4 77.9 88.8 86.3 80.1 88.  82.2 80.8 85.9
 82.5 84.3 84.9 88.5 85.4 86.2 56.1 79.1 77.1 85.6 78.1 76.2 88.6 78.7
 78.  78.6 79.7 88.9 83.2 79.  57.3 81.5 79.5 85.2 78.2 81.2 87.9 82.
 86.1 80.9 77.6 87.6 83.1 82.7 74.8 55.6 75.4]
[ 4489.  3462.  3032.  3500.  8157.  9937.  5598.  3504.  3580. 24491.
  5553.  5790.  4141.  4078.  6996.  5717. 16925.  7573.  3308.  6321.
  9428. 10509.  9309. 10179.  4694.  4960.  7168. 12225.  3818.  4916.
  9253.  6609.  6312.  6204.  5365.  8085.  5815.  4492.  7798.  4604.
  7206.  4964.  3777.  7699.  9530.  4970.  6026.  8735.  4232.  4427.
  4745.  1227.  4435.  5130.  2673.  5651.  3384.  8995.  9368.  8513.
  2852.  2828.  6839.  3147.  5186.  4297.  3784.  4063.  4172. 15850.
  5925.  2841.  6978.  8955.  6368.  6363. 11869.  3831.  5055.  4413.
 12208.  2144.  5209.  7995.  4780.  8477.  4781.  3390.  7980.  4851.
  3976.  3984.  7822.  5146.  3992. 10080.  8427.  4908.  6270. 12275.
  4087.  4243.  3934.  1108.  3932.  4878.  2418. 11190.  3833.  6593.
  7040.  2978.  2924. 16265.  4302.  5823.  3860.  4164. 10260.  5682.
 15994.  6418.  3247.  8040. 10191.  5238.  8381. 12771.  3527.  5797.
  4687. 11491.  2833.  4544.  8665.  4754.  8708.  3737.  5301.  9136.
  4782.  4086.  5052.  4205.  8254.  5445.  4284.  8690.  7934.  5140.
  7490. 10221.  4161.  4350.  3556.  1025.  2356.  4770.  2120.  6054.
  3636.  7668.  6534.  6520.  2670.  1814. 11528.  4962.  5571.  4061.
  3959.  6014.  6805.  8070.  5754.  3010.  9154. 12532.  5882.  7763.
 11091.  3460.  5332.  4883. 11322.  1971.  4266.  4209.  9369.  3134.
  4064.  9409.  3812.  4861.  5116.  4957.  4202.  8089.  8623.  7213.
  9443.  3841.  3505.  3466.  1589.  3208.  3315.  3918.  7458.  3646.
  4703.  7354.  5775.  2483.  2173.  5376.  5646.  5036.  2350.  6658.
  6546. 12670.  3826.  3204.  9312. 10768.  5758.  6497. 11110.  3045.
  8935.  4676. 10825.  1975.  4813.  5126.  4600. 26384.  3728.  4180.
  9744.  3412.  4045.  4582.  3961.  6573.  5324.  3323.  7191.  7598.
  6923.  9699.  4988.  4520.  3199.  1048.  2138.   872.]